version: '3.8'

services:
  k6:
    image: grafana/k6
    container_name: k6_test_runner
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PLATFORM=web
    command: run --out json=result.json src/${PLATFORM}-main.js
